projects/700c/web/views/general.py
import flask

from web.models import User, Status, Trip
from web.views.util import requires_login, lookup_request_user


mod = flask.Blueprint('general', __name__)

mod.before_request(lookup_request_user)


@mod.route('/', methods=['GET'])
@requires_login
def index():
    active_trip = Trip.get_active(flask.g.user.id)

    if active_trip is None:
        return flask.redirect(flask.url_for('trip.index'))

    return flask.render_template('views/timeline.html', **{
        'active_trip': active_trip,
        'statuses': Status.get_recent(flask.g.user.id)
    })


@mod.route('/login', methods=['POST'])
def try_login():
    form = flask.request.form
    user = User.by_name_and_password(form['user'], form['password'])

    if user is not None:
        flask.session['uid'] = user.id
        return flask.redirect('/')

    return flask.redirect('/login')


@mod.route('/login', methods=['GET'])
def login():
    return flask.render_template('views/login.html')


@mod.route('/logout', methods=['GET'])
def logout():
    flask.session.pop('uid')
    flask.flash('Logged out!')
    return flask.redirect(flask.url_for('general.login'))


@mod.route('/register', methods=['GET'])
def register():
    raise NotImplementedError("no")

projects/700c/web/views/user.py
import flask

from web.models import Trip, User
from web.views.util import lookup_request_user


mod = flask.Blueprint('user', __name__)
mod.before_request(lookup_request_user)


@mod.route('/<int:id>', methods=['GET'])
def view(id):
    return flask.render_template('views/user.html', **{
        'user': User.by_id(id, raise_on_not_found=True),
        'trips': Trip.by_user_id(id)
    })


@mod.route('/<int:id>/edit', methods=['POST'])
def edit(id):
    raise NotImplementedError('no')

projects/700c/web/templates/layouts/base.html
<!doctype html>

<title>{% block title %}{% endblock %}</title>

<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">

<link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">

<header class="header">
  <nav class="header__nav">
    <ul>
      <li>
        <a href="{{ url_for('general.index') }}">
          <b>700c</b>
        </a>
      </li>
      {% if g.logged_in %}
      <li>
        <a href="{{ url_for('user.view', id=g.user.id) }}">
          <span>{{ g.user.name }}</span>
        </a>
      </li>
      <li><a href="{{ url_for('general.logout') }}">Log Out</a></li>
      {% else %}
      <li><a href="{{ url_for('general.register') }}">Register</a></li>
      <li><a href="{{ url_for('general.login') }}">Log In</a></li>
      {% endif %}
    </ul>
  </nav>
</header>

<main class="main">
  {% block header %}{% endblock %}

  {% for message in get_flashed_messages() %}
  <div class="flash">{{ message }}</div>
  {% endfor %}

  {% block content %}{% endblock %}
</main>