projects/700c/web/views/trip.py
import flask
from flask import request, url_for

from web.models import Status, Trip
from web.views.util import requires_login, lookup_request_user


mod = flask.Blueprint('trip', __name__)
mod.before_request(lookup_request_user)


@mod.route('/')
@requires_login
def index(methods=['GET']):
    return flask.render_template('views/create_trip.html', **{})


@mod.route('/create', methods=['POST'])
@requires_login
def create():
    # TODO: real form parsing

    Trip.create(
        title=request.form['title'],
        description=request.form['description'],
        user_id=flask.g.user.id)

    return flask.redirect(url_for('general.index'))


@mod.route('/<int:id>', methods=['GET'])
@mod.route('/<int:id>-<string:slug>', methods=['GET'])
def view(id, slug=''):
    trip = Trip.by_id(id, raise_on_not_found=True)

    return flask.render_template('views/trip.html', **{
        'trip': trip,
        'statuses': Status.by_trip_id(id)
    })


@mod.route('/<int:id>/edit', methods=['POST'])
def edit(id):
    values = {
        k: request.form[k]
        for k in ['title', 'description']
        if k in request.form
    }

    trip = Trip.update(where=(Trip.ended_at is None), values=values)

    return flask.redirect(url_for('trip.view', id, trip.slug))

projects/700c/web/views/user.py
import flask

from web.models import Trip, User
from web.views.util import lookup_request_user


mod = flask.Blueprint('user', __name__)
mod.before_request(lookup_request_user)


@mod.route('/<int:id>', methods=['GET'])
def view(id):
    return flask.render_template('views/user.html', **{
        'user': User.by_id(id, raise_on_not_found=True),
        'trips': Trip.by_user_id(id)
    })


@mod.route('/<int:id>/edit', methods=['POST'])
def edit(id):
    raise NotImplementedError('no')

projects/700c/web/templates/views/create_trip.html
{% extends 'layouts/base.html' %}

{% block content %}
  <div class="trip">
    <div class="form form--trip trip__create">
      <form action="/trip/create" method="post" autocomplete="off">
        <input class="form__input"
               type="text"
               name="title"
               placeholder="Start a new trip"
               required>
        <textarea class="form__input form__input--textarea"
                  name="description"
                  placeholder="Description..."
                  required></textarea>
        <input class="form__input form__input--submit"
               type="submit"
               value="Embark">
      </form>
    </div>
  </div>
{% endblock %}

projects/700c/web/templates/views/login.html
{% extends 'layouts/base.html' %}

{% block content %}
<div class="login">
  <form class="form form--trip" action="/login" method="post">
    <p><input type="text"     name="user"     placeholder="username"></p>
    <p><input type="password" name="password" placeholder="password"></p>

    <p><input type="submit" value="login"></p>
  </form>
</div>
{% endblock %}

projects/700c/web/templates/views/timeline.html
{% extends 'layouts/base.html' %}

{% block content %}
  <div>
    {% if active_trip is not none %}
      {% include 'partials/create_status.html' %}
      <h2 class="trip__title">{{ active_trip.title }}</h2>

    {% endif %}

    {% include 'partials/status_list.html' %}
  </div>

{% endblock %}

projects/700c/web/templates/views/trip.html
{% extends 'layouts/base.html' %}

{% block content %}
  <div class="trip">
    <h1 class="trip__title">{{ trip.title }}</h1>
    <p class="trip__description">{{trip.description}}</p>

    {% include 'partials/status_list.html' %}
  </div>
{% endblock %}

projects/700c/web/templates/views/user.html
{% extends 'layouts/base.html' %}

{% block content %}
  <div class="user">
    <h1>{{ user.name }}</h1>
    <p>
      {% if user.bio is not none %}
        {{ user.bio }}
      {% endif %}
    </p>

    <h2>Trips</h2>
    <div class="user__trips">
      {% if trips.items|length == 0 %}
        <p>
          Looks like {{user.name}} hasn't started any trips yet!
        </p>
        {% if user.id == g.user.id %}
          <p>
            <a href="{{ url_for('trip.index') }}">Start a trip</a>
          </p>
        {% endif %}
      {% endif %}

      <ul>
        {% for trip in trips.items %}
          <li class="user__trips__trip">
            <h3>
              <a href="{{ url_for('trip.view', id=trip.id, slug=trip.slug) }}">
                {{ trip.title }}
              </a>
            </h3>
            <p>{{trip.description}}</p>
          </li>
        {% endfor %}

        {# TODO: handle pagination #}
      </ul>

    </div>

  </div>
{% endblock %}